# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v3
kind: Config
metadata:
  name: document-status-service
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: document-status-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: document-status-service
  port: 80
  localPort: 8894
deploy:
  kubectl: { }
manifests:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: document-status-service
      requires:
      - image: common
        alias: BASE_IMG
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/custom
- name: prod_non_cloudbuild
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod
- name: prod
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: document-status-service
      docker:
        cacheFrom:
          - document-status-service
          - document-status-service:latest
      requires:
      - image: common
        alias: BASE_IMG
- name: dev
  build:
    googleCloudBuild: {}
    artifacts:
    - image: document-status-service
      docker:
        cacheFrom:
          - document-status-service
          - document-status-service:latest
      requires:
        - image: common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kubectl: { }
  manifests:
    kustomize:
      paths:
      - ./kustomize/dev