# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: fileserver-{{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1T
  nfs:
    path: /lookerfiles
    server: {{ .Values.nfs.serverIp | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: fileserver-claim-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1T
  storageClassName: ""
  volumeName: fileserver-{{ .Release.Name }}