apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: looker-secrets-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secrets.project }}/secrets/{{ .Values.secrets.dbPassSecretName }}/versions/latest"
        fileName: looker_db_pass
      - resourceName: "projects/{{ .Values.secrets.project }}/secrets/{{ .Values.secrets.gcmKeySecretName }}/versions/latest"
        fileName: looker_gcm_key
  provider: gcp
  secretObjects:
  - data:
    - key: gcm-key
      objectName: looker_gcm_key
    - key: db-pass
      objectName: looker_db_pass
    secretName: looker-secrets-{{ .Release.Name }}
    type: Opaque
{{- if .Values.options.userProvisioning.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    {{- include "looker.nodeLabels" . | nindent 4 }}
  name: looker-user-provisioning-secrets-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secrets.project }}/secrets/{{ .Values.options.userProvisioning.provisionerSecretName }}/versions/latest"
        fileName: user_provision
  provider: gcp
  secretObjects:
  - data:
    - key: provisioner
      objectName: user_provision
    secretName: looker-user-provision-{{ .Release.Name }}
    type: Opaque
{{- end }}